# Generated by Django 3.2.9 on 2021-11-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='next_earnings',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='login_id',
            field=models.CharField(default='E5A1AF15', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasecoupon',
            name='code',
            field=models.CharField(default='1D487D63', max_length=50),
        ),
    ]
