# Generated by Django 3.2.9 on 2021-11-10 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211110_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 12, 7, 51, 31, 50672, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='login_id',
            field=models.CharField(default='F9AF3E8A', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasecoupon',
            name='code',
            field=models.CharField(default='E2EC6C1D', max_length=50),
        ),
    ]
