# Generated by Django 3.2.9 on 2021-12-02 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211110_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='days',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 4, 5, 1, 39, 262259, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='login_id',
            field=models.CharField(default='5FAFE2B1', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasecoupon',
            name='code',
            field=models.CharField(default='2409A091', max_length=50),
        ),
    ]
