# Generated by Django 3.2.9 on 2021-12-02 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211202_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 4, 20, 56, 58, 9429, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='login_id',
            field=models.CharField(default='868A8C80', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasecoupon',
            name='code',
            field=models.CharField(default='C099A58F', max_length=50),
        ),
    ]
