# Generated by Django 3.2.9 on 2021-12-03 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211202_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='account',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 5, 8, 4, 50, 182662, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='login_id',
            field=models.CharField(default='42EF2277', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasecoupon',
            name='code',
            field=models.CharField(default='2906CF29', max_length=50),
        ),
    ]
